pipeline {
    agent any

    tools {
        nodejs 'node18' // You’ll configure this name in Jenkins tools
    }

    environment {
        CI = 'true' // Needed for Vite build
    }

    stages {
       stage('Clone Repo') {
    steps {
        git branch: 'main', url: 'https://github.com/vamshikrishna12376/rohan.co.git'
    }
}
        stage('Install Dependencies') {
            steps {
                sh 'npm ci || npm install'
            }
        }

        
        stage('Build') {
            steps {
                sh 'npm run build'
            }
        }
    }

    post {
        success {
            echo '🎉 React App Built Successfully!'
        }
        failure {
            echo '❌ Build Failed!'
        }
    }
}
